# SQLite

version: "3.7"

services:
  sqlite:
    image: sqlite
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=database.db
      - SQLITE_USER=user
      - SQLITE_PASSWORD=qwerty
      - SQLITE_ROOT_PASSWORD=password
